pragma foreign_keys = ON; 
BEGIN TRANSACTION;
CREATE TABLE "Customer" (
 "ID" TEXT NOT NULL UNIQUE,
 "Name" TEXT,
 "Phone" INTEGER,
 PRIMARY KEY("ID")
);
CREATE TABLE "Room" (
 "ID" TEXT NOT NULL UNIQUE,
 "Type" TEXT,
 PRIMARY KEY("ID")
);
CREATE TABLE "Reservation" (
 "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 "StartDate" TEXT,
 "EndDate" TEXT,
 "CustomerID" TEXT,
 "RoomID" TEXT,
 FOREIGN KEY("CustomerID") REFERENCES Customer("ID"),
 FOREIGN KEY("RoomID") REFERENCES Room("ID")
);
CREATE TABLE "RoomType" (
 "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 "Name" TEXT,
 "Price" NUMERIC
);
COMMIT;
