pragma foreign_keys = ON; 
BEGIN TRANSACTION;
CREATE TABLE "Client" (
 "CID" TEXT NOT NULL UNIQUE,
 "Name" TEXT,
 "Phone" TEXT,
 PRIMARY KEY("CID")
);
CREATE TABLE "Room" (
 "RID" TEXT NOT NULL UNIQUE,
 "Type" INTEGER,
 PRIMARY KEY("RID"),
 FOREIGN KEY("Type") REFERENCES RoomType("RTID")
);
CREATE TABLE "Reservation" (
 "RESID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 "StartDate" TEXT,
 "EndDate" TEXT,
 "ClientID" TEXT,
 "RoomID" TEXT,
 "Price" NUMERIC,
 "Paid" INTEGER,
 FOREIGN KEY("ClientID") REFERENCES Client("CID"),
 FOREIGN KEY("RoomID") REFERENCES Room("RID")
);
CREATE TABLE "RoomType" (
 "RTID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 "Name" TEXT,
 "Price" NUMERIC
);
COMMIT;
